### ISSUE TITLE
develop branchの追加

### ISSUE THREAD

**Issue by ryo628** [ss-koishi/cue-simulator#2]
GitFlow を採用するため、developbranchを作る

**Comment by ryo628** [comment]
@ss-koishi master branchの保護お願いします 🙇 
https://help.github.com/ja/github/administering-a-repository/configuring-protected-branches

**Comment by ryo628** [comment]
あとdevelopへのmerge制限かな？

**Comment by ss-koishi** [comment]
仕事終わったらやります
